### ISSUE TITLE
Sprint & Jump as Animatronic

### ISSUE THREAD

**Issue by svensonic1** [ucchyocean/Five-Nights-at-Freddy-s-in-Minecraft#17]
Animatronics can bypass slow walking by holding sprint (2x w or holding CTRL on keyboard) and jumping forward this makes them faster. Fix this please

**Comment by ucchyocean** [comment]
Oh, I want you to write that request things at bukkit dev...  This is not a request form.
But, I will think about an Animatronics.
Do you have an idea of the details skill of Animatronics?

**Comment by ucchyocean** [comment]
wontfix.

Could not make the details specification.
Sprint skill is not so interested, because other characters have a speed skill already.
Jump skill is not so interested too. Why do you need the jumping?
