### ISSUE TITLE
Feature request: Allow conigurable equip for animatronics

### ISSUE THREAD

**Issue by Malachiel87** [ucchyocean/Five-Nights-at-Freddy-s-in-Minecraft#23]
since i found some cool texture pack that use iron ore, gold ore as 3d heads of chica and bonnie i would like a option to see if is possible to configure these thing into configurations (normal hats dont work as 3d hats and should be ores on heads)
Here i am wearing gold iron set + gold iron ore as hat:
http://i.imgur.com/xkoLs8k.png
Texture used: https://www.dropbox.com/s/pd7sni7m9pdaulc/Faithful%20to%20FNaF.zip?dl=0

If you will do it i will you all my babies <3

**Comment by ucchyocean** [comment]
So sorry, I could not understand you said clearly.
Could you write more easier English?

**Comment by Malachiel87** [comment]
I just mean:
Add in configuration to allow user to change inventory of animatronics, allowing to use any item type also as head (like gold_ore) because some texture pack use ores block for 3d models :3

**Comment by ucchyocean** [comment]
So sorry, I'm so confusing. Why head only? Why gold ore? Why not a helmet??
Please give me a time.

**Comment by Malachiel87** [comment]
because, some texture pack use ores for create 3d model, helmets are not renderizable, check this screenshot: http://i.imgur.com/xkoLs8k.png actual i am wearing a iron ore as hat...

**Comment by ucchyocean** [comment]
So sorry, I could not understand you said clearly.
Please give me a time to learn 3d models.

**Comment by Malachiel87** [comment]
So i do simplest:
i want use your plugin with that resource pack.

**Comment by ucchyocean** [comment]
So sorry, I'm so confusing. Why head only? Why gold ore? Why not a helmet??
If your said is true, I must learn 3d models at first.

**Comment by Malachiel87** [comment]
because ores have sub id that allow to create more detailed texture pack of that item, you don't need to learn, just add configuration in the plugin for customize animatronic item equip :3

**Comment by ucchyocean** [comment]
> because ores have sub id that allow to create more detailed texture pack of that item

Why? Why helmet cannot have that id?

**Comment by Malachiel87** [comment]
check also hypixel server, they use ores model, or wood for create 3d cars.

**Comment by ucchyocean** [comment]
So sorry, I don't know hypixel server. What is that?

Please give me a time to learn 3d models. Don't reply for now. Don't disturb my learning.

**Comment by ucchyocean** [comment]
Fixed at commit @440e3c01458cdae27f7d65e7e346ab2062a3d36c.
